import * as THREE from "https://unpkg.com/three@0.164.1/build/three.module.js";
const REARTH_PER_RJUP=11.209,RJUP_PER_RSUN=.102763,RSUN_AU=.00465047;
const state={systems:[],selected:null,samples:[],phase:.5,playing:true,mode:"observatory",lastTime:performance.now(),scene:null,controls:{u1:.35,u2:.2,noise:220,cadence:60,moon:false,starspot:false,ttv:false,moonRadius:.27,moonSep:5,spotAmp:400}};
const el={};["btnLoadCache","btnTryNasa","fileInput","dataStatus","targetCount","dataSource","targetSelect","systemOverview","u1","u1Out","u2","u2Out","noise","noiseOut","cadence","cadenceOut","moonToggle","spotToggle","ttvToggle","moonRadius","moonRadiusOut","moonSep","moonSepOut","spotAmp","spotAmpOut","btnDownloadLightcurve","btnDownloadDataset","btnExportPng","webglCanvas","lightcurveCanvas","residualCanvas","qualityCanvas","miniCanvas","playPause","phaseSlider","phaseOut","selectedName","fluxNow","timeToMid","midTransitMetric","depthMetric","durationMetric","impactMetric","rmsMetric","sampleCount","inTransitCount","minFluxMetric","chiMetric","snrMetric","noiseMetric","geometryReadout","eventConsole","educationalOverlay","liveBadge"].forEach(id=>el[id]=document.getElementById(id));
function log(m,t="ok"){const d=document.createElement("div");d.className=t;d.textContent=`${new Date().toLocaleTimeString()}  ${m}`;el.eventConsole.prepend(d)}function fmt(v,d=2){return Number.isFinite(v)?Number(v).toFixed(d):"—"}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function radiusRatio(r){if(!r.st_rad||r.st_rad<=0)return null;if(r.pl_radj&&r.pl_radj>0)return r.pl_radj*RJUP_PER_RSUN/r.st_rad;if(r.pl_rade&&r.pl_rade>0)return(r.pl_rade/REARTH_PER_RJUP)*RJUP_PER_RSUN/r.st_rad;return null}
function semiMajorAxisOverRs(r){if(r.pl_orbsmax&&r.pl_orbsmax>0&&r.st_rad&&r.st_rad>0)return r.pl_orbsmax/(r.st_rad*RSUN_AU);const P=r.pl_orbper||3,M=r.st_mass||1,a=Math.cbrt(Math.max(.01,M)*(P/365.25)**2);return a/((r.st_rad||1)*RSUN_AU)}
function norm(raw){const r={};Object.entries(raw).forEach(([k,v])=>{const n=Number(v);r[k]=Number.isFinite(n)&&v!==""?n:v});const rr=radiusRatio(r);if(!rr||!r.pl_orbper||!r.st_rad)return null;const inc=Number(r.pl_orbincl||89),aRs=semiMajorAxisOverRs(r),b=aRs*Math.cos(inc*Math.PI/180),earth=r.pl_rade||(r.pl_radj?r.pl_radj*REARTH_PER_RJUP:rr*r.st_rad/RJUP_PER_RSUN*REARTH_PER_RJUP),depth=r.pl_trandep||rr*rr*1e6,dur=r.pl_trandur||estimateDuration(r.pl_orbper,rr,aRs,b);return{id:String(r.pl_name||"unknown"),planetName:String(r.pl_name||"unknown"),hostName:String(r.hostname||"unknown"),period:+r.pl_orbper,aAu:+(r.pl_orbsmax||aRs*r.st_rad*RSUN_AU),planetRadiusEarth:+earth,planetRadiusJupiter:+(r.pl_radj||earth/REARTH_PER_RJUP),planetMassJupiter:+(r.pl_bmassj||0),inclination:inc,transitDepthPpm:+depth,transitDurationHours:+dur,stellarRadius:+r.st_rad,stellarMass:+(r.st_mass||1),stellarTeff:+(r.st_teff||5772),distancePc:+(r.sy_dist||0),discoveryMethod:String(r.discoverymethod||"Transit"),radiusRatio:rr,aRs,impact:b}}
function estimateDuration(P,p,aRs,b){const chord=Math.sqrt(Math.max(0,(1+p)**2-b*b)),arg=clamp(chord/Math.max(1e-6,aRs),0,1);return P*24/Math.PI*Math.asin(arg)}
function parseCSV(txt){const lines=txt.trim().split(/\r?\n/).filter(Boolean),h=lines[0].split(",").map(s=>s.trim());return lines.slice(1).map(line=>{const vals=[];let cur="",q=false;for(const ch of line){if(ch=='"')q=!q;else if(ch==","&&!q){vals.push(cur);cur=""}else cur+=ch}vals.push(cur);const o={};h.forEach((x,i)=>o[x]=vals[i]?.replace(/^"|"$/g,""));return o})}
async function loadStaticCache(){el.dataStatus.textContent="loading";log("Loading local static exoplanet cache");const r=await fetch("data/exoplanets.json",{cache:"no-store"});if(!r.ok)throw Error("Could not load data/exoplanets.json");useRows(await r.json(),"static curated cache")}
async function tryNasaLive(){el.dataStatus.textContent="querying NASA";log("Trying NASA Exoplanet Archive TAP", "warn");const q=`SELECT TOP 450 pl_name,hostname,pl_orbper,pl_orbsmax,pl_rade,pl_radj,pl_bmassj,pl_orbincl,pl_trandep,pl_trandur,st_rad,st_mass,st_teff,sy_dist,discoverymethod FROM pscomppars WHERE tran_flag=1 AND pl_orbper IS NOT NULL AND st_rad IS NOT NULL AND (pl_rade IS NOT NULL OR pl_radj IS NOT NULL) ORDER BY pl_trandep DESC`;try{const r=await fetch("https://exoplanetarchive.ipac.caltech.edu/TAP/sync?"+new URLSearchParams({query:q,format:"json"}));if(!r.ok)throw Error(`NASA TAP HTTP ${r.status}`);useRows(await r.json(),"NASA TAP live")}catch(e){log(`NASA live query blocked/failed: ${e.message}`,"bad");if(!state.systems.length)await loadStaticCache()}}
function useRows(rows,src){const systems=rows.map(norm).filter(Boolean).sort((a,b)=>b.transitDepthPpm-a.transitDepthPpm);state.systems=systems;el.targetSelect.innerHTML="";systems.forEach((s,i)=>{const o=document.createElement("option");o.value=String(i);o.textContent=`${s.planetName} · ${Math.round(s.transitDepthPpm)} ppm · ${s.hostName}`;el.targetSelect.appendChild(o)});el.targetCount.textContent=String(systems.length);el.dataSource.textContent=src;el.dataStatus.textContent="locked";log(`Loaded ${systems.length} target systems from ${src}`);selectSystem(0)}
function selectSystem(i){state.selected=state.systems[i]||null;if(!state.selected)return;el.targetSelect.value=String(i);if(state.scene)state.scene.setSystem(state.selected);regenerate()}
function bindUI(){el.btnLoadCache.onclick=loadStaticCache;el.btnTryNasa.onclick=tryNasaLive;el.targetSelect.onchange=e=>selectSystem(+e.target.value);[["u1","u1Out","u1"],["u2","u2Out","u2"],["noise","noiseOut","noise"],["cadence","cadenceOut","cadence"],["moonRadius","moonRadiusOut","moonRadius"],["moonSep","moonSepOut","moonSep"],["spotAmp","spotAmpOut","spotAmp"]].forEach(([id,out,key])=>{el[id].oninput=()=>{state.controls[key]=+el[id].value;el[out].textContent=String(state.controls[key]);regenerate()}});[["moonToggle","moon"],["spotToggle","starspot"],["ttvToggle","ttv"]].forEach(([id,key])=>{el[id].onchange=()=>{state.controls[key]=el[id].checked;regenerate()}});el.phaseSlider.oninput=()=>{state.phase=+el.phaseSlider.value;renderAll()};el.playPause.onclick=()=>{state.playing=!state.playing;el.playPause.textContent=state.playing?"Pause":"Play";el.liveBadge.textContent=state.playing?"● live acquiring":"paused"};document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.mode=b.dataset.mode;el.educationalOverlay.classList.toggle("hidden",state.mode!=="education");renderAll()});el.fileInput.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const txt=await f.text();useRows(f.name.endsWith(".json")?JSON.parse(txt):parseCSV(txt),`uploaded ${f.name}`)};el.btnDownloadLightcurve.onclick=downloadLightcurve;el.btnDownloadDataset.onclick=()=>download("exolight_current_dataset.json",JSON.stringify(state.systems,null,2),"application/json");el.btnExportPng.onclick=()=>{const a=document.createElement("a");a.href=el.lightcurveCanvas.toDataURL("image/png");a.download="exolight_lightcurve.png";a.click()}}
const grid=makeGrid(82,150);function makeGrid(R,A){const pts=[];for(let i=0;i<R;i++){const r0=i/R,r1=(i+1)/R,r=Math.sqrt((r0*r0+r1*r1)/2),area=Math.PI*(r1*r1-r0*r0)/A;for(let j=0;j<A;j++){const p=j/A*Math.PI*2;pts.push({x:r*Math.cos(p),y:r*Math.sin(p),r,area})}}return pts}
function I(r,u1,u2){const mu=Math.sqrt(Math.max(0,1-r*r));return Math.max(0,1-u1*(1-mu)-u2*(1-mu)**2)}
function flux(occ,u1,u2){let tot=0,blk=0;for(const pt of grid){const inten=I(pt.r,u1,u2)*pt.area;tot+=inten;for(const o of occ){const dx=pt.x-o.x,dy=pt.y-o.y;if(dx*dx+dy*dy<=o.r*o.r){blk+=inten;break}}}return clamp(1-blk/tot,0,1)}
function sep(ph,aRs,inc){const th=2*Math.PI*ph,x=aRs*Math.sin(th),y=aRs*Math.cos(th)*Math.cos(inc);return{x,y,z:Math.hypot(x,y)}}
function noise(i,ppm){const u=(Math.sin(i*12.9898+78.233)*43758.5453)%1,v=(Math.sin(i*93.989+12.1)*24634.6345)%1;return Math.sqrt(-2*Math.log(Math.max(1e-6,Math.abs(u))))*Math.cos(2*Math.PI*Math.abs(v))*ppm/1e6}
function generate(sys,c){const p=sys.radiusRatio,aRs=sys.aRs,inc=sys.inclination*Math.PI/180,periodH=sys.period*24,dur=Math.max(.25,sys.transitDurationHours),win=Math.max(2,dur*3.6),N=clamp(Math.round(win*3600/c.cadence),240,2200),arr=[];for(let i=0;i<N;i++){let t=-win/2+i/(N-1)*win,ttv=c.ttv?.08*Math.sin(2*Math.PI*.15+i*.003):0,s=sep((t+ttv)/periodH,aRs,inc),occ=[{x:s.x,y:s.y,r:p}];if(c.moon){const ma=i/N*Math.PI*2*1.7+.13,mo=p*c.moonSep;occ.push({x:s.x+mo*Math.cos(ma),y:s.y+mo*Math.sin(ma)*.38,r:p*c.moonRadius})}let model=flux(occ,c.u1,c.u2),obs=model+noise(i,c.noise);if(c.starspot&&model<.9999){obs+=c.spotAmp/1e6*Math.exp(-.5*((t+dur*.12)/(dur*.10))**2)}arr.push({index:i,timeHours:t,phaseOrbit:(t+ttv)/periodH,x:s.x,y:s.y,z:s.z,model,observed:obs,residual:obs-model,inTransit:model<.999999})}return arr}
class TransitScene{constructor(canvas){this.canvas=canvas;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setClearColor(0x010204,0);this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(38,1,.01,300);this.camera.position.set(0,.55,6.2);this.scene.add(new THREE.AmbientLight(0x77aaff,.55));const L=new THREE.PointLight(0xffcc88,8.5,80);L.position.set(0,0,2.2);this.scene.add(L);this.star=this.makeStar();this.scene.add(this.star);this.glow=this.makeGlow();this.scene.add(this.glow);this.planet=this.makePlanet();this.scene.add(this.planet);this.moon=this.makeMoon();this.scene.add(this.moon);this.orbit=this.makeOrbit();this.scene.add(this.orbit);this.chord=this.makeChord();this.scene.add(this.chord);this.addStars();this.resize();addEventListener("resize",()=>this.resize());this.animate()}
makeStar(){const g=new THREE.SphereGeometry(1.35,96,96),m=new THREE.ShaderMaterial({vertexShader:`varying vec3 n;varying vec3 p;void main(){n=normalize(mat3(modelMatrix)*normal);p=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform vec3 c;uniform float u1;uniform float u2;varying vec3 n;varying vec3 p;void main(){vec3 v=normalize(cameraPosition-p);float mu=clamp(dot(normalize(n),v),0.,1.);float limb=1.-u1*(1.-mu)-u2*pow(1.-mu,2.);float rim=pow(1.-mu,2.2);gl_FragColor=vec4(c*limb+vec3(1.,.52,.12)*rim*.16,1.);}`,uniforms:{c:{value:new THREE.Color(1,.72,.32)},u1:{value:.35},u2:{value:.2}}});return new THREE.Mesh(g,m)}
makeGlow(){const g=new THREE.SphereGeometry(1.48,96,96),m=new THREE.ShaderMaterial({side:THREE.BackSide,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,vertexShader:`varying vec3 n;varying vec3 p;void main(){n=normalize(mat3(modelMatrix)*normal);p=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform vec3 c;varying vec3 n;varying vec3 p;void main(){vec3 v=normalize(cameraPosition-p);float f=pow(1.-abs(dot(normalize(n),v)),2.);gl_FragColor=vec4(c,f*.38);}`,uniforms:{c:{value:new THREE.Color(1,.56,.12)}}});return new THREE.Mesh(g,m)}
makePlanet(){return new THREE.Mesh(new THREE.SphereGeometry(1,64,64),new THREE.MeshStandardMaterial({color:0x06101d,roughness:.68,metalness:.12,emissive:0x02070c,emissiveIntensity:.45}))}
makeMoon(){const x=new THREE.Mesh(new THREE.SphereGeometry(1,32,32),new THREE.MeshStandardMaterial({color:0x101a22,roughness:.8}));x.visible=false;return x}
makeOrbit(){const pts=[],r=2.55;for(let i=0;i<=300;i++){const a=i/300*Math.PI*2;pts.push(new THREE.Vector3(Math.sin(a)*r,Math.cos(a)*.45,Math.cos(a)*.55))}return new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x35f2d0,transparent:true,opacity:.25}))}
makeChord(){const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-3.25,0,.18),new THREE.Vector3(3.25,0,.18)]),new THREE.LineDashedMaterial({color:0xffffff,transparent:true,opacity:.30,dashSize:.12,gapSize:.08}));line.computeLineDistances();return line}
addStars(){const n=1400,pos=new Float32Array(n*3);for(let i=0;i<n;i++){const r=30+Math.random()*120,th=Math.random()*Math.PI*2,ph=Math.acos(2*Math.random()-1);pos[i*3]=r*Math.sin(ph)*Math.cos(th);pos[i*3+1]=r*Math.sin(ph)*Math.sin(th);pos[i*3+2]=r*Math.cos(ph)}const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.BufferAttribute(pos,3));this.scene.add(new THREE.Points(g,new THREE.PointsMaterial({color:0x9edfff,size:.035,transparent:true,opacity:.5,blending:THREE.AdditiveBlending,depthWrite:false})))}
setSystem(sys){this.sys=sys;const col=tempColor(sys.stellarTeff);this.star.material.uniforms.c.value=col;this.glow.material.uniforms.c.value=col.clone().lerp(new THREE.Color(1,.48,.10),.35);this.planet.scale.setScalar(clamp(sys.radiusRatio*1.85,.08,.36))}
update(s){if(!this.sys||!s)return;const x=clamp(s.x/(1+this.sys.radiusRatio),-2.6,2.6),y=clamp(s.y,-1.15,1.15);this.planet.position.set(x,y,1.42);this.planet.rotation.y+=.006;this.moon.visible=state.controls.moon;if(state.controls.moon){const ps=clamp(this.sys.radiusRatio*1.85,.08,.36),ms=ps*state.controls.moonRadius,a=s.index/state.samples.length*Math.PI*2*1.7+.13;this.moon.scale.setScalar(ms);this.moon.position.set(this.planet.position.x+Math.cos(a)*ps*state.controls.moonSep*.75,this.planet.position.y+Math.sin(a)*ps*state.controls.moonSep*.25,1.48)}this.star.material.uniforms.u1.value=state.controls.u1;this.star.material.uniforms.u2.value=state.controls.u2}
resize(){const r=this.canvas.getBoundingClientRect();this.camera.aspect=Math.max(1,r.width)/Math.max(1,r.height);this.camera.updateProjectionMatrix();this.renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false)}
animate=()=>{requestAnimationFrame(this.animate);this.star.rotation.y+=.0015;this.glow.rotation.y+=.0015;this.renderer.render(this.scene,this.camera)}}
function tempColor(k){const t=clamp(k,2500,11000)/100;let r,g,b;if(t<=66){r=255;g=99.4708025861*Math.log(t)-161.1195681661;b=t<=19?0:138.5177312231*Math.log(t-10)-305.0447927307}else{r=329.698727446*Math.pow(t-60,-.1332047592);g=288.1221695283*Math.pow(t-60,-.0755148492);b=255}return new THREE.Color(clamp(r,0,255)/255,clamp(g,0,255)/255,clamp(b,0,255)/255)}
function updateReadouts(){const s=state.selected;if(!s)return;el.selectedName.textContent=s.planetName;el.systemOverview.innerHTML=metrics([["Star",s.hostName],["Planet",s.planetName],["Type",s.discoveryMethod],["Distance",`${fmt(s.distancePc,1)} pc`],["Period",`${fmt(s.period,4)} d`],["Radius",`${fmt(s.planetRadiusEarth,2)} R⊕`],["Mass",`${fmt(s.planetMassJupiter,2)} Mj`],["Teff",`${Math.round(s.stellarTeff)} K`]]);el.geometryReadout.innerHTML=metrics([["Rp/Rs",fmt(s.radiusRatio,4)],["a/Rs",fmt(s.aRs,2)],["Inclination",`${fmt(s.inclination,2)}°`],["Impact b",fmt(s.impact,3)],["Depth",`${Math.round(s.transitDepthPpm)} ppm`],["Duration",`${fmt(s.transitDurationHours,2)} h`]]);el.depthMetric.textContent=`${Math.round(s.transitDepthPpm)} ppm`;el.durationMetric.textContent=`${fmt(s.transitDurationHours,2)} h`;el.impactMetric.textContent=fmt(s.impact,3)}
function metrics(rows){return rows.map(([k,v])=>`<div><b>${k}</b><span>${v}</span></div>`).join("")}
function regenerate(){if(!state.selected)return;state.samples=generate(state.selected,state.controls);updateReadouts();renderAll()}
function renderAll(){if(!state.samples.length)return;const i=clamp(Math.floor(state.phase*(state.samples.length-1)),0,state.samples.length-1),s=state.samples[i];state.scene?.update(s);el.phaseSlider.value=String(state.phase);el.phaseOut.textContent=fmt(state.phase,4);el.fluxNow.textContent=fmt(s.observed,5);el.timeToMid.textContent=`${fmt(s.timeHours*60,1)} min`;const minF=Math.min(...state.samples.map(x=>x.model)),rms=Math.sqrt(state.samples.reduce((a,x)=>a+x.residual*x.residual,0)/state.samples.length),inT=state.samples.filter(x=>x.inTransit).length,depth=(1-minF)*1e6,snr=depth/Math.max(1,state.controls.noise);el.sampleCount.textContent=state.samples.length.toLocaleString();el.inTransitCount.textContent=inT.toLocaleString();el.minFluxMetric.textContent=fmt(minF,6);el.rmsMetric.textContent=`${Math.round(rms*1e6)} ppm`;el.chiMetric.textContent=fmt((rms*1e6/Math.max(1,state.controls.noise))**2,2);el.snrMetric.textContent=fmt(snr,1);el.noiseMetric.textContent=`${state.controls.noise} ppm`;drawLC(el.lightcurveCanvas,state.samples,i,false);drawRes(el.residualCanvas,state.samples,i);drawQuality(el.qualityCanvas,snr);drawLC(el.miniCanvas,state.samples,i,true)}
function setup(c){const d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect();c.width=Math.max(1,Math.floor(r.width*d));c.height=Math.max(1,Math.floor(r.height*d));const ctx=c.getContext("2d");ctx.setTransform(d,0,0,d,0,0);return{ctx,w:r.width,h:r.height}}
function drawLC(c,arr,idx,mini){const{ctx,w,h}=setup(c),p=mini?{l:28,r:14,t:14,b:22}:{l:62,r:26,t:30,b:44};ctx.fillStyle="rgba(1,2,4,.82)";ctx.fillRect(0,0,w,h);if(!arr.length)return;const minT=arr[0].timeHours,maxT=arr.at(-1).timeHours,minF=Math.min(...arr.map(s=>s.observed),...arr.map(s=>s.model)),yMin=Math.max(.88,minF-Math.max(.001,(1-minF)*.16)),yMax=1.006,x=t=>p.l+(t-minT)/(maxT-minT)*(w-p.l-p.r),y=f=>p.t+(1-(f-yMin)/(yMax-yMin))*(h-p.t-p.b);ctx.strokeStyle="rgba(148,163,184,.13)";for(let i=0;i<=6;i++){let yy=p.t+i/6*(h-p.t-p.b);ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(w-p.r,yy);ctx.stroke()}for(let i=0;i<=8;i++){let xx=p.l+i/8*(w-p.l-p.r);ctx.beginPath();ctx.moveTo(xx,p.t);ctx.lineTo(xx,h-p.b);ctx.stroke()}ctx.fillStyle="rgba(53,242,208,.75)";for(let i=0;i<arr.length;i+=mini?7:3)ctx.fillRect(x(arr[i].timeHours),y(arr[i].observed),mini?1:1.4,mini?1:1.4);ctx.strokeStyle="rgba(255,189,106,.95)";ctx.lineWidth=mini?1.5:2.1;ctx.beginPath();arr.forEach((s,i)=>i?ctx.lineTo(x(s.timeHours),y(s.model)):ctx.moveTo(x(s.timeHours),y(s.model)));ctx.stroke();const a=arr[idx];ctx.strokeStyle="rgba(255,255,255,.42)";ctx.setLineDash([5,7]);ctx.beginPath();ctx.moveTo(x(a.timeHours),p.t);ctx.lineTo(x(a.timeHours),h-p.b);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="rgba(234,242,255,.75)";ctx.font=`${mini?8:11}px JetBrains Mono`;ctx.textAlign="left";ctx.fillText("Normalized Flux",p.l,mini?10:18);if(!mini){ctx.textAlign="center";ctx.fillText("Time from Mid-Transit [hours]",w/2,h-10)}ctx.textAlign="right";ctx.fillStyle="rgba(53,242,208,.8)";ctx.fillText(`min ${fmt(minF,5)}`,w-p.r,mini?10:18)}
function drawRes(c,arr,idx){const{ctx,w,h}=setup(c),p={l:50,r:20,t:28,b:38};ctx.fillStyle="rgba(1,2,4,.82)";ctx.fillRect(0,0,w,h);if(!arr.length)return;const maxA=Math.max(50e-6,...arr.map(s=>Math.abs(s.residual)))*1.1,minT=arr[0].timeHours,maxT=arr.at(-1).timeHours,x=t=>p.l+(t-minT)/(maxT-minT)*(w-p.l-p.r),y=r=>p.t+(1-(r+maxA)/(2*maxA))*(h-p.t-p.b);ctx.strokeStyle="rgba(148,163,184,.13)";for(let i=0;i<=4;i++){let yy=p.t+i/4*(h-p.t-p.b);ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(w-p.r,yy);ctx.stroke()}ctx.strokeStyle="rgba(255,255,255,.35)";ctx.beginPath();ctx.moveTo(p.l,y(0));ctx.lineTo(w-p.r,y(0));ctx.stroke();ctx.fillStyle="rgba(53,242,208,.8)";for(let i=0;i<arr.length;i+=3)ctx.fillRect(x(arr[i].timeHours),y(arr[i].residual),1.25,1.25);ctx.strokeStyle="rgba(255,189,106,.85)";ctx.setLineDash([5,7]);ctx.beginPath();ctx.moveTo(x(arr[idx].timeHours),p.t);ctx.lineTo(x(arr[idx].timeHours),h-p.b);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="rgba(234,242,255,.75)";ctx.font="11px JetBrains Mono";ctx.fillText("ΔFlux residual",p.l,18)}
function drawQuality(c,snr){const{ctx,w,h}=setup(c);ctx.fillStyle="rgba(1,2,4,.82)";ctx.fillRect(0,0,w,h);const cx=w*.33,cy=h*.55,r=Math.min(w,h)*.32,f=clamp(snr/40,0,1);ctx.strokeStyle="rgba(53,242,208,.12)";ctx.lineWidth=9;ctx.beginPath();ctx.arc(cx,cy,r,Math.PI*.75,Math.PI*2.25);ctx.stroke();ctx.strokeStyle=snr>10?"#42ff95":snr>4?"#ffbd6a":"#ff4d6d";ctx.beginPath();ctx.arc(cx,cy,r,Math.PI*.75,Math.PI*.75+Math.PI*1.5*f);ctx.stroke();ctx.fillStyle="#eaf2ff";ctx.font="900 24px JetBrains Mono";ctx.textAlign="center";ctx.fillText(fmt(snr,1),cx,cy+8);ctx.font="700 10px JetBrains Mono";ctx.fillStyle="#35f2d0";ctx.fillText("SNR",cx,cy+28);ctx.strokeStyle="rgba(53,242,208,.65)";ctx.lineWidth=1.2;ctx.beginPath();for(let i=0;i<80;i++){const xx=w*.58+i/79*w*.34,yy=h*.52+Math.sin(i*.34)*8+noise(i,180)*12000;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)}ctx.stroke()}
function download(n,t,m="text/plain"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type:m}));a.download=n;a.click();URL.revokeObjectURL(a.href)}
function downloadLightcurve(){if(!state.samples.length)return;const head="index,time_hours,phase_orbit,z,model_flux,observed_flux,residual,in_transit\n",rows=state.samples.map(s=>[s.index,s.timeHours,s.phaseOrbit,s.z,s.model,s.observed,s.residual,s.inTransit].join(",")).join("\n");download(`exolight_${state.selected.planetName.replaceAll(" ","_")}_lightcurve.csv`,head+rows,"text/csv")}
function tick(now){const dt=Math.min(.05,(now-state.lastTime)/1000);state.lastTime=now;if(state.playing&&state.samples.length){state.phase=(state.phase+dt*.045)%1;renderAll()}requestAnimationFrame(tick)}
function init(){bindUI();state.scene=new TransitScene(el.webglCanvas);loadStaticCache().catch(e=>log(e.message,"bad"));requestAnimationFrame(tick);log("Mission control loaded. Static GitHub Pages mode active.")}
init();
