import { useEffect, useRef } from "react";
import { useExoStore } from "../state/useExoStore";

function setup(canvas: HTMLCanvasElement){ const dpr=Math.min(devicePixelRatio,2); const r=canvas.getBoundingClientRect(); canvas.width=Math.max(1,r.width*dpr); canvas.height=Math.max(1,r.height*dpr); const ctx=canvas.getContext("2d")!; ctx.setTransform(dpr,0,0,dpr,0,0); return {ctx,w:r.width,h:r.height}; }

export function LightCurveDock(){
  const ref=useRef<HTMLCanvasElement|null>(null); const model=useExoStore(s=>s.model); const setPhase=useExoStore(s=>s.setPhaseCursor); const phase=useExoStore(s=>s.phaseCursor);
  useEffect(()=>{ const canvas=ref.current; if(!canvas) return; const {ctx,w,h}=setup(canvas); ctx.clearRect(0,0,w,h); ctx.fillStyle="#010204"; ctx.fillRect(0,0,w,h); if(!model.length)return; const p={l:58,r:24,t:24,b:40}; const minX=model[0].phase,maxX=model[model.length-1].phase,minY=Math.min(...model.map(m=>m.modelFlux))-0.0008,maxY=1.002; const x=(v:number)=>p.l+(v-minX)/(maxX-minX)*(w-p.l-p.r); const y=(v:number)=>p.t+(1-(v-minY)/(maxY-minY))*(h-p.t-p.b); ctx.strokeStyle="rgba(148,163,184,.14)"; for(let i=0;i<=6;i++){const yy=p.t+i/6*(h-p.t-p.b);ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(w-p.r,yy);ctx.stroke()} ctx.strokeStyle="#ffbd6a"; ctx.lineWidth=2.2; ctx.beginPath(); model.forEach((m,i)=>i?ctx.lineTo(x(m.phase),y(m.modelFlux)):ctx.moveTo(x(m.phase),y(m.modelFlux))); ctx.stroke(); ctx.strokeStyle="rgba(255,255,255,.45)"; ctx.setLineDash([5,7]); ctx.beginPath(); ctx.moveTo(x(phase),p.t); ctx.lineTo(x(phase),h-p.b); ctx.stroke(); ctx.setLineDash([]); ctx.fillStyle="#eaf2ff"; ctx.font="12px JetBrains Mono"; ctx.fillText("GPU/CPU transit model flux",p.l,16); },[model,phase]);
  return <section className="panel plot-panel"><div className="panel-header"><h2>Light Curve Workspace</h2><span>drag phase</span></div><canvas ref={ref} onPointerMove={e=>{ if(e.buttons!==1 || !ref.current || !model.length) return; const r=ref.current.getBoundingClientRect(); const u=(e.clientX-r.left)/r.width; const min=model[0].phase,max=model[model.length-1].phase; setPhase(min+u*(max-min)); }}/></section>;
}
