import{GOLD_SQL,fetchNASA,loadBootstrap,normalize}from'./data/nasa.js';import{makeLightCurve}from'./physics/transit.js';import{OrreryScene}from'./render/scene.js';import{drawCurve,drawResiduals}from'./render/plots.js';
const $=id=>document.getElementById(id),ids=['btnNASA','btnBootstrap','targetSelect','targetInfo','rp','a','inc','ecc','omega','rpOut','aOut','iOut','eOut','wOut','c1','c2','c3','c4','c1Out','c2Out','c3Out','c4Out','spot','moon','filter','downloadCSV','upload','scene','curve','phase','resid','status','fluxNow','phaseNow','telemetry','console','sql'];const els=Object.fromEntries(ids.map(id=>[id,$(id)]));els.sql.textContent=GOLD_SQL;const state={targets:[],target:null,params:null,curve:[],phase:.5,scene:null};
function log(m,t='ok'){const d=document.createElement('div');d.className=t;d.textContent=new Date().toLocaleTimeString()+'  '+m;els.console.prepend(d)}function fmt(v,d=3){return Number.isFinite(v)?Number(v).toFixed(d):'—'}
function paramsFromTarget(t){return{rpRs:t.rpRs,aRs:t.aRs,incDeg:t.inc,ecc:t.ecc,omegaDeg:t.omega,limb:[+els.c1.value,+els.c2.value,+els.c3.value,+els.c4.value],spot:els.spot.checked,moon:els.moon.checked,noisePpm:220,teff:t.teff}}
function setTargets(rows,src){state.targets=rows.map(normalize).filter(Boolean);els.targetSelect.innerHTML='';state.targets.forEach((t,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${t.pl_name} · ${Math.round(t.depth)} ppm · ${t.hostname}`;els.targetSelect.appendChild(o)});log(`Loaded ${state.targets.length} targets from ${src}`);selectTarget(0)}
function selectTarget(i){state.target=state.targets[i];if(!state.target)return;state.params=paramsFromTarget(state.target);syncControls();recompute()}
function syncControls(){const p=state.params;els.rp.value=p.rpRs;els.a.value=p.aRs;els.inc.value=p.incDeg;els.ecc.value=p.ecc;els.omega.value=p.omegaDeg;updateOuts()}
function updateOuts(){els.rpOut.textContent=(+els.rp.value).toFixed(3);els.aOut.textContent=(+els.a.value).toFixed(1);els.iOut.textContent=(+els.inc.value).toFixed(2)+'°';els.eOut.textContent=(+els.ecc.value).toFixed(3);els.wOut.textContent=(+els.omega.value).toFixed(0)+'°';['c1','c2','c3','c4'].forEach(id=>els[id+'Out'].textContent=(+els[id].value).toFixed(2))}
function readParams(){state.params={...state.params,rpRs:+els.rp.value,aRs:+els.a.value,incDeg:+els.inc.value,ecc:+els.ecc.value,omegaDeg:+els.omega.value,limb:[+els.c1.value,+els.c2.value,+els.c3.value,+els.c4.value],spot:els.spot.checked,moon:els.moon.checked,teff:state.target?.teff||5772,noisePpm:220}}
function recompute(){if(!state.params)return;readParams();updateOuts();state.curve=makeLightCurve(state.params,1000);state.scene.setParams(state.params);render();updatePanels();els.status.textContent='MODEL LOCKED'}
function updatePanels(){const t=state.target,p=state.params;if(!t)return;els.targetInfo.innerHTML=[['Host',t.hostname],['Planet',t.pl_name],['Period',fmt(t.period,5)+' d'],['Depth',Math.round(t.depth)+' ppm'],['Duration',fmt(t.duration,2)+' h'],['Teff',Math.round(t.teff)+' K'],['Vmag',fmt(t.vmag,2)]].map(([a,b])=>`<div><b>${a}</b><span>${b}</span></div>`).join('');const rms=Math.sqrt(state.curve.reduce((s,d)=>s+d.residual*d.residual,0)/state.curve.length)*1e6;els.telemetry.innerHTML=[['Rp/Rs',fmt(p.rpRs,4)],['a/Rs',fmt(p.aRs,2)],['Inclination',fmt(p.incDeg,2)+'°'],['Eccentricity',fmt(p.ecc,3)],['ω',fmt(p.omegaDeg,0)+'°'],['Residual RMS',Math.round(rms)+' ppm'],['Filter',els.filter.value.toUpperCase()],['Samples',state.curve.length]].map(([a,b])=>`<div><b>${a}</b><span>${b}</span></div>`).join('')}
function render(){if(!state.curve.length)return;const idx=Math.floor(state.phase*(state.curve.length-1)),c=state.curve[idx];state.scene.update(state.phase);els.fluxNow.textContent='Flux '+c.model.toFixed(5);els.phaseNow.textContent='Phase '+state.phase.toFixed(3);drawCurve(els.curve,state.curve,idx,'Light curve: observed cyan / model amber');drawCurve(els.phase,state.curve,idx,'Phase-fold workspace');drawResiduals(els.resid,state.curve,idx)}
async function initNASA(){try{els.status.textContent='QUERYING NASA';setTargets(await fetchNASA(log),'NASA Archive TAP')}catch(e){log('NASA browser query failed: '+e.message,'bad');log('Loading bootstrap targets. Run scripts/build-target-list.py for 200+ candidates.','warn');setTargets(await loadBootstrap(),'local bootstrap')}}
function downloadCSV(){const rows=['phase,model_flux,observed_flux,residual'].concat(state.curve.map(d=>`${d.phase},${d.model},${d.observed},${d.residual}`)).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows],{type:'text/csv'}));a.download='exointel_lightcurve.csv';a.click();URL.revokeObjectURL(a.href)}
function bind(){els.btnNASA.onclick=initNASA;els.btnBootstrap.onclick=async()=>setTargets(await loadBootstrap(),'local bootstrap');els.targetSelect.onchange=e=>selectTarget(+e.target.value);['rp','a','inc','ecc','omega','c1','c2','c3','c4','spot','moon','filter'].forEach(id=>els[id].addEventListener('input',recompute));els.downloadCSV.onclick=downloadCSV;els.upload.onchange=e=>log('Upload received: '+(e.target.files[0]?.name||''),'ok');document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
function loop(){state.phase=(state.phase+0.00045)%1;render();requestAnimationFrame(loop)}state.scene=new OrreryScene(els.scene);bind();updateOuts();initNASA();loop();
